version: "3.9"

services:
  db:
    image: postgres:16-alpine      # Postgres 16 + vector
    container_name: match-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SQL_HELPERS:/temp/SQL_HELPERS

volumes:
  pgdata:
